<?php

namespace TradeTracker\AssesmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SetupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetupRepository extends EntityRepository
{
}
