variable "project_name" {}
variable "access_key" {}
variable "secret_key" {}
variable "region" { default = "us-east-1"}
variable "key_name" {}
variable "az_a" {}
variable "az_b" {}
variable "my_ip" {}
variable "vpc_cidr_us" {}
variable "public_subnet_cidr_a_us" {}
variable "public_subnet_cidr_b_us" {}
variable "private_subnet_cidr_a_us" {}
variable "private_subnet_cidr_b_us" {}
variable "nat_userdata_us" {}
variable "ami-us-east-1" {}
variable "nat_instance_type" {}
variable "puppet_instance_type" {}
variable "instance_tag" {}
variable "instance_count" {}
variable "puppet_userdata_us" {}
variable "sg_name" {}
variable "source_cidr_block" {}
variable "mongo_userdata_us" {}
variable "mongo_instance_type" {}
variable "mongo_instance_count" {}
variable "mongo_instance_tag" {}
variable "pg_userdata_us" {}
variable "pg_instance_count" {}
variable "pg_instance_tag" {}
variable "pg_instance_type" {}
variable "pgpool_userdata_us" {}
variable "pgpool_instance_tag" {}
variable "pgpool_instance_count" {}
variable "web_instance_type" {}
variable "web_instance_tag" {}
variable "web_userdata_us" {}
variable "web_sg_name" {}
variable "elb_name" {}
variable "listner_port" {}
variable "instance_role" {}
variable "role_name" {}
variable "web_ami" {}
variable "as_zones" {}
variable "asg_max" {}
variable "asg_min" {}
variable "asg_desired" {}
variable "as_user_data" {}
